package com.example.perfume_store.modules.perfume.mapper;

import com.example.perfume_store.common.response.PageResponse;
import com.example.perfume_store.domain.brand.Brand;
import com.example.perfume_store.domain.note.Note;
import com.example.perfume_store.domain.note_perfume.NotePerfume;
import com.example.perfume_store.domain.note_perfume.NoteType;
import com.example.perfume_store.domain.perfume.Concentration;
import com.example.perfume_store.domain.perfume.Gender;
import com.example.perfume_store.domain.perfume.Perfume;
import com.example.perfume_store.domain.volume.Volume;
import com.example.perfume_store.domain.volume_perfume.VolumePerfume;
import com.example.perfume_store.modules.perfume.dto.request.NotePerfumeRequestDTO;
import com.example.perfume_store.modules.perfume.dto.request.PerfumeCreateRequestDTO;
import com.example.perfume_store.modules.perfume.dto.request.PerfumeUpdateRequestDTO;
import com.example.perfume_store.modules.perfume.dto.request.VolumePerfumeRequestDTO;
import com.example.perfume_store.modules.perfume.dto.response.NotePerfumeResponseDTO;
import com.example.perfume_store.modules.perfume.dto.response.PerfumeDetailsResponseDTO;
import com.example.perfume_store.modules.perfume.dto.response.PerfumePublicResponseDTO;
import com.example.perfume_store.modules.perfume.entity.SampleImage;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.PageImpl;
import org.springframework.data.domain.PageRequest;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import static org.assertj.core.api.Assertions.assertThat;

class PerfumeMapperTest {

    private PerfumeMapper perfumeMapper;

    @BeforeEach
    void setUp() {
        // PerfumeMapperImpl will be generated by MapStruct
        perfumeMapper = new PerfumeMapperImpl();
    }

    @Test
    @DisplayName("toDetailsResponseDTO: Should map all fields correctly")
    void toDetailsResponseDTO_ShouldMapAllFields() {
        // Arrange
        Perfume perfume = createPerfume(1, "Chanel No.5");
        perfume.setVolumePerfumes(List.of(createVolumePerfume(1, 100, new BigDecimal("150.00"), perfume)));
        perfume.setNotePerfumes(List.of(
                createNotePerfume(1, "Rose", NoteType.Heart, perfume),
                createNotePerfume(2, "Lemon", NoteType.Top, perfume)
        ));

        // Act
        PerfumeDetailsResponseDTO result = perfumeMapper.toDetailsResponseDTO(perfume);

        // Assert
        assertThat(result).isNotNull();
        assertThat(result.getId()).isEqualTo(1);
        assertThat(result.getName()).isEqualTo("Chanel No.5");
        assertThat(result.getBrand()).isEqualTo("Chanel");
        assertThat(result.getSampleImages()).containsExactly("url1");
        assertThat(result.getVolumes()).hasSize(1);
        assertThat(result.getVolumes().get(0).getVolume()).isEqualTo(100);
        assertThat(result.getNotes().getTop()).containsExactly("Lemon");
        assertThat(result.getNotes().getHeart()).containsExactly("Rose");
    }

    @Test
    @DisplayName("mapNotes: Should group notes by type")
    void mapNotes_ShouldGroupNotesByType() {
        // Arrange
        List<NotePerfume> notes = List.of(
                createNotePerfume(1, "Top Note", NoteType.Top, null),
                createNotePerfume(2, "Heart Note", NoteType.Heart, null),
                createNotePerfume(3, "Base Note", NoteType.Base, null)
        );

        // Act
        NotePerfumeResponseDTO result = perfumeMapper.mapNotes(notes);

        // Assert
        assertThat(result.getTop()).containsExactly("Top Note");
        assertThat(result.getHeart()).containsExactly("Heart Note");
        assertThat(result.getBase()).containsExactly("Base Note");
    }

    @Test
    @DisplayName("toPublicResponseDTO: Should map fields and calculate minPrice")
    void toPublicResponseDTO_ShouldMapAndCalculateMinPrice() {
        // Arrange
        Perfume perfume = createPerfume(1, "Dior Sauvage");
        perfume.setVolumePerfumes(Arrays.asList(
                createVolumePerfume(1, 50, new BigDecimal("100.00"), perfume),
                createVolumePerfume(2, 100, new BigDecimal("80.00"), perfume)
        ));

        // Act
        PerfumePublicResponseDTO result = perfumeMapper.toPublicResponseDTO(perfume);

        // Assert
        assertThat(result.getName()).isEqualTo("Dior Sauvage");
        assertThat(result.getMinPrice()).isEqualByComparingTo("80.00");
        assertThat(result.getSampleImage()).isEqualTo("url1");
    }

    @Test
    @DisplayName("toPublicPageResponse: Should map page and content correctly")
    void toPublicPageResponse_ShouldMapPage() {
        // Arrange
        int id = 1;
        String name = "Perfume 1";
        List<Perfume> perfumes = List.of(createPerfume(id, name));

        // Tạo Page: trang 0 (trang đầu), size 10, tổng 1 phần tử
        Page<Perfume> page = new PageImpl<>(perfumes, PageRequest.of(0, 10), 1);

        // Act
        PageResponse<PerfumePublicResponseDTO> result = perfumeMapper.toPublicPageResponse(page);

        // Assert
        // 1. Kiểm tra Mapping Metadata (Phân trang)
        assertThat(result.getPage()).isEqualTo(1); // 0 + 1
        assertThat(result.getTotalPages()).isEqualTo(1);
        assertThat(result.getTotalElements()).isEqualTo(1L);
        assertThat(result.getSize()).isEqualTo(10);
        assertThat(result.isFirst()).isTrue();
        assertThat(result.isLast()).isTrue();

        // 2. Kiểm tra Mapping Content (Dữ liệu thực)
        assertThat(result.getContent()).hasSize(1);
        PerfumePublicResponseDTO dto = result.getContent().getFirst();
        assertThat(dto.getName()).isEqualTo(name); // Đảm bảo field trong list được map đúng
    }

    @Test
    @DisplayName("toEntity: Should map create request to entity")
    void toEntity_ShouldMapCreateRequest() {
        // Arrange
        PerfumeCreateRequestDTO request = createPerfumeCreateRequestDTO("New Perfume");

        // Act
        Perfume result = perfumeMapper.toEntity(request);

        // Assert
        assertThat(result.getName()).isEqualTo("New Perfume");
        assertThat(result.getDescription()).isEqualTo("Description");
        assertThat(result.getGender()).isEqualTo(Gender.Unisex);
        assertThat(result.getConcentration()).isEqualTo(Concentration.EDP);
        assertThat(result.getSampleImages()).isNull(); // Ignored in mapper
    }

    @Test
    @DisplayName("updateEntity: Should update existing entity")
    void updateEntity_ShouldUpdateFields() {
        // Arrange
        Perfume perfume = createPerfume(1, "Old Name");
        PerfumeUpdateRequestDTO request = new PerfumeUpdateRequestDTO();
        request.setName("Updated Name");
        request.setHide(true);

        // Act
        perfumeMapper.updateEntity(perfume, request);

        // Assert
        assertThat(perfume.getName()).isEqualTo("Updated Name");
        assertThat(perfume.isHide()).isTrue();
    }

    // --- Private Helper Methods (Data Factories) ---

    private Perfume createPerfume(int id, String name) {
        Perfume perfume = new Perfume();
        perfume.setId(id);
        perfume.setName(name);
        perfume.setGender(Gender.Unisex);
        perfume.setConcentration(Concentration.EDP);
        perfume.setDescription("Description");
        perfume.setBrand(createBrand(1, "Chanel"));
        
        List<SampleImage> images = new ArrayList<>();
        images.add(createSampleImage(1, "url1", perfume));
        perfume.setSampleImages(images);
        perfume.setVolumePerfumes(new ArrayList<>());

        return perfume;
    }

    private Brand createBrand(int id, String name) {
        Brand brand = new Brand();
        brand.setId(id);
        brand.setName(name);
        return brand;
    }

    private SampleImage createSampleImage(int id, String path, Perfume perfume) {
        SampleImage image = new SampleImage();
        image.setId(id);
        image.setPath(path);
        image.setPerfume(perfume);
        return image;
    }

    private VolumePerfume createVolumePerfume(int id, int volumeValue, BigDecimal price, Perfume perfume) {
        VolumePerfume vp = new VolumePerfume();
        vp.setId(id);
        vp.setPrice(price);
        vp.setPerfume(perfume);
        
        Volume v = new Volume();
        v.setId(id);
        v.setVolume(volumeValue);
        vp.setVolume(v);
        
        return vp;
    }

    private NotePerfume createNotePerfume(int id, String noteName, NoteType type, Perfume perfume) {
        NotePerfume np = new NotePerfume();
        np.setId(id);
        np.setType(type);
        np.setPerfume(perfume);
        
        Note n = new Note();
        n.setId(id);
        n.setName(noteName);
        np.setNote(n);
        
        return np;
    }

    private PerfumeCreateRequestDTO createPerfumeCreateRequestDTO(String name) {
        PerfumeCreateRequestDTO dto = new PerfumeCreateRequestDTO();
        dto.setName(name);
        dto.setDescription("Description");
        dto.setGender(Gender.Unisex);
        dto.setConcentration(Concentration.EDP);
        dto.setBrandId(1);
        
        VolumePerfumeRequestDTO vReq = new VolumePerfumeRequestDTO();
        vReq.setVolumeId(1);
        vReq.setPrice(new BigDecimal("100.00"));
        dto.setVolumes(List.of(vReq));
        
        NotePerfumeRequestDTO nReq = new NotePerfumeRequestDTO();
        nReq.setNoteId(1);
        nReq.setType(NoteType.Top);
        dto.setNotes(List.of(nReq));
        
        return dto;
    }
}
