version: '3.8'

services:
  mysql:
    image: mysql:8.1
    environment:
      LANG: C.UTF-8 # Set the interpreter to uft8 instead of latin1
      MYSQL_ALLOW_EMPTY_PASSWORD: yes     # Allow the root password to be empty
      MYSQL_USER: ${MYSQL_USERNAME}       # Create a user that can only operate in the MYSQL_DATABASE
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}   # Name of the default database to create
    ports:
      - "3307:3306"
    volumes:
      - ./database:/docker-entrypoint-initdb.d  # Base on all the files in ./database to create db

  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333" # Port for Dashboard & REST API
      - "6334:6334" # Port for gRPC
    volumes:
      - ./qdrant_storage:/qdrant/storage:z

  backend:
    build: .
    ports:
      - "8081:8080"
    depends_on:
      - mysql
      - qdrant
    environment:
      # --- Database Envs ---
      MYSQL_URL: ${MYSQL_URL}
      MYSQL_USERNAME: ${MYSQL_USERNAME}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}

      # --- Qdrant Envs (Cấu hình để Spring kết nối vào service qdrant) ---
      QDRANT_HOST: qdrant
      QDRANT_PORT: 6334

      # --- SSO/OAuth2 Envs ---
      SSO_CLIENT_ID: ${SSO_CLIENT_ID}
      SSO_CLIENT_SECRET: ${SSO_CLIENT_SECRET}

      # --- Security & JWT Envs ---
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRATION: ${JWT_EXPIRATION}

      # --- Cloudinary Envs ---
      CLOUDINARY_NAME: ${CLOUDINARY_NAME}
      CLOUDINARY_KEY: ${CLOUDINARY_KEY}
      CLOUDINARY_SECRET: ${CLOUDINARY_SECRET}