server:
  tomcat:
    max-part-count: 50  # Change the default parts limitation when sending form-data (10 parts)
  port: 8080

spring:
  # Startup logs
  main:
    banner-mode: off
    log-startup-info: off

  application:
    name: perfume_store

  # Datasource environments, imported by Intellij Envs Run Config in development
  datasource:
    url: ${MYSQL_URL}
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}

  # JPA and Hibernate
  jpa:
    hibernate:
      ddl-auto: none  # Do nothing with the real schema when entities have changes
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect # Tells Hibernate what SQL syntax db uses

  # SSO
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${SSO_CLIENT_ID}
            client-secret: ${SSO_CLIENT_SECRET}
            scope:
              - email
              - profile
  servlet:
    multipart:
      resolve-lazily: true
      max-file-size: 10MB
      max-request-size: 50MB

  ai:
    openai:
      api-key: ${GROQ_API_KEY}
      base-url: https://api.groq.com/openai
      chat:
        options:
          model: llama-3.3-70b-versatile
          temperature: 0.7
        enabled: true
      embedding:
        enabled: false # Disable OpenAI embedding because Groq doesn't support it
    ollama:
      base-url: http://localhost:11434
      embedding:
        options:
          model: mxbai-embed-large
        enabled: true
      chat:
        enabled: false
    vectorstore:
      qdrant:
        host: ${QDRANT_HOST:localhost}
        port: ${QDRANT_PORT:6334}
        collection-name: ${QDRANT_COLLECTION:perfume_collection}
        use-tls: false
jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION}

app:
  frontend-url: ${FRONTEND_URL:http://localhost:5173}

cloudinary:
  name: ${CLOUDINARY_NAME}
  key: ${CLOUDINARY_KEY}
  secret: ${CLOUDINARY_SECRET}

# ------ Turn on when debugging -------------
#logging:
#  level:
#    org:
#      apache:
#        tomcat:
#          util:
#            http:
#              fileupload: DEBUG
#
#      springframework:
#        web: DEBUG
