package com.example.perfume_store.modules.brand.mapper;

import static org.assertj.core.api.Assertions.assertThat;

import com.example.perfume_store.domain.brand.Brand;
import com.example.perfume_store.modules.brand.dto.request.BrandRequestDTO;
import com.example.perfume_store.modules.brand.dto.response.BrandResponseDTO;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

import java.util.List;

class BrandMapperTest {

    private BrandMapper brandMapper;

    @BeforeEach
    void setUp() {
        // This class is generated by MapStruct
        brandMapper = new BrandMapperImpl();
    }

    @Test
    @DisplayName("toResponseDTO: Should map Brand Entity to BrandResponseDTO")
    void toResponseDTO_EntityToDTO_Success() {
        // Arrange
        Brand entity = new Brand();
        entity.setId(1);
        entity.setName("Chanel");
        entity.setHide(false);

        // Act
        BrandResponseDTO result = brandMapper.toResponseDTO(entity);

        // Assert
        assertThat(result).isNotNull();
        assertThat(result.getId()).isEqualTo(entity.getId());
        assertThat(result.getName()).isEqualTo(entity.getName());
        assertThat(result.isHide()).isEqualTo(entity.isHide());
    }

    @Test
    @DisplayName("toResponseDTO: Should map list of Entities to list of DTOs")
    void toResponseDTO_ListEntitiesToListDTOs_Success() {
        // Arrange
        Brand brand1 = new Brand();
        brand1.setName("Dior");

        Brand brand2 = new Brand();
        brand2.setName("Gucci");

        List<Brand> entities = List.of(brand1, brand2);

        // Act
        List<BrandResponseDTO> result = brandMapper.toResponseDTO(entities);

        // Assert
        assertThat(result).hasSize(2);
        assertThat(result).extracting(BrandResponseDTO::getName)
                .containsExactly("Dior", "Gucci");
    }

    @Test
    @DisplayName("toEntity: Should map BrandRequestDTO to Brand Entity")
    void toEntity_RequestDTOToEntity_Success() {
        // Arrange
        BrandRequestDTO dto = new BrandRequestDTO();
        dto.setName("Hermes");
        dto.setHide(true);

        // Act
        Brand result = brandMapper.toEntity(dto);

        // Assert
        assertThat(result).isNotNull();
        assertThat(result.getName()).isEqualTo(dto.getName());
        assertThat(result.isHide()).isEqualTo(dto.isHide());
        // ID must be 0 or null because RequestDTO doesn't have ID
        assertThat(result.getId()).isZero();
    }

    @Test
    @DisplayName("updateEntity: Should update existing Entity from RequestDTO")
    void updateEntity_Success() {
        // Arrange
        Brand existingBrand = new Brand();
        existingBrand.setId(99);
        existingBrand.setName("Old Name");
        existingBrand.setHide(false);

        BrandRequestDTO updateDTO = new BrandRequestDTO();
        updateDTO.setName("New Name");
        updateDTO.setHide(true);

        // Act
        brandMapper.updateEntity(existingBrand, updateDTO);

        // Assert
        assertThat(existingBrand.getId()).isEqualTo(99); // ID không được thay đổi
        assertThat(existingBrand.getName()).isEqualTo("New Name");
        assertThat(existingBrand.isHide()).isTrue();
    }

    @Test
    @DisplayName("toResponseDTO: Should return null when input entity is null")
    void toResponseDTO_NullInput_ReturnsNull() {
        assertThat(brandMapper.toResponseDTO((Brand) null)).isNull();
    }
}